# Generated by Django 2.2 on 2019-04-17 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('start_amount', models.FloatField()),
                ('zero_interest_date', models.DateField()),
                ('biller_address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('notes', models.CharField(max_length=255)),
                ('web_link', models.CharField(max_length=255)),
                ('bill_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneybags.Bill_States')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_amount', models.FloatField()),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneybags.Bills')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_date', models.DateField()),
                ('income_amount', models.FloatField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneybags.IncomeSource')),
            ],
        ),
    ]
