# Generated by Django 2.2 on 2019-04-18 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='bill_state',
        ),
    ]
